name: Cleanup

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  cleanup:
    name: Delete all resources associated with pr
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        shell: bash
        run: |
          echo "SUFFIX=pr-${{ github.event.number }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Clean up
        uses: bcgov/openshift-launchpad-deployment@master
        with:
          AUTH_TOKEN: ${{ secrets.OC_DEV_TOKEN_EDIT }}
          SCRIPT: openshift/scripts/oc_cleanup.sh ${SUFFIX} apply
